const fs = require('fs');
const path = require('path');

const storePath = path.join(__dirname, 'database', 'local_store.json');
let store = JSON.parse(fs.readFileSync(storePath, 'utf8'));

const seedQuestions = [
  // ================= KHTN 6 =================
  {
    id: "q-khtn6-b18-01",
    grade: 6,
    semester: "HK1",
    lessonId: "lesson-6-18",
    topic: "Tế bào – Đơn vị cơ bản của sự sống",
    subjectArea: "BIOLOGY",
    contentDomain: "LIVING_THINGS",
    learningRequirementText: "Nêu được khái niệm tế bào, nhận biết được tế bào là đơn vị cấu trúc của sự sống.",
    cognitiveLevel: "M1",
    questionType: "MCQ",
    difficulty: "EASY",
    questionText: "Đơn vị cấu trúc cơ bản cấu tạo nên mọi cơ thể sinh vật là gì?",
    options: [
      { key: "A", text: "Mô" },
      { key: "B", text: "Tế bào" },
      { key: "C", text: "Cơ quan" },
      { key: "D", text: "Hệ cơ quan" }
    ],
    correctAnswer: "B",
    explanation: "Tất cả các sinh vật sống từ đơn bào đến đa bào đều được cấu tạo từ một hoặc nhiều tế bào.",
    rationale: "Câu hỏi yêu cầu học sinh nhớ lại định nghĩa tế bào là đơn vị cấu trúc của sự sống (Nhận biết - M1).",
    score: 0.25,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 6 Kết nối tri thức", lessonName: "Bài 18: Tế bào" },
    tags: ["BIOLOGY", "LIVING_THINGS", "M1", "MCQ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn6-b19-01",
    grade: 6,
    semester: "HK1",
    lessonId: "lesson-6-19",
    topic: "Cấu tạo và chức năng các thành phần của tế bào",
    subjectArea: "BIOLOGY",
    contentDomain: "LIVING_THINGS",
    learningRequirementText: "Phân biệt được tế bào động vật và tế bào thực vật thông qua quan sát hình ảnh.",
    cognitiveLevel: "M2",
    questionType: "MCQ",
    difficulty: "MEDIUM",
    questionText: "Bào quan nào sau đây có ở tế bào thực vật nhưng KHÔNG có ở tế bào động vật?",
    options: [
      { key: "A", text: "Màng tế bào" },
      { key: "B", text: "Chất tế bào" },
      { key: "C", text: "Lục lạp" },
      { key: "D", text: "Nhân tế bào" }
    ],
    correctAnswer: "C",
    explanation: "Lục lạp và thành tế bào cellulose là đặc trưng có ở tế bào thực vật mà tế bào động vật không có.",
    rationale: "Yêu cầu phân biệt thành phần đặc trưng giữa tế bào thực vật và tế bào động vật (Thông hiểu - M2).",
    score: 0.25,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 6 Kết nối tri thức", lessonName: "Bài 19: Cấu tạo tế bào" },
    tags: ["BIOLOGY", "LIVING_THINGS", "M2", "MCQ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn6-b10-01",
    grade: 6,
    semester: "HK1",
    lessonId: "lesson-6-10",
    topic: "Các thể của chất và sự chuyển thể",
    subjectArea: "CHEMISTRY",
    contentDomain: "SUBSTANCE_CHANGE",
    learningRequirementText: "Trình bày được quá trình diễn ra sự chuyển thể của chất: nóng chảy, đông đặc, bay hơi, ngưng tụ.",
    cognitiveLevel: "M2",
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    questionText: "Khi quan sát hiện tượng chuyển thể của nước trong tự nhiên, các nhận định sau đây là đúng hay sai?",
    options: [
      { key: "a", text: "Sự chuyển từ thể lỏng sang thể hơi (khí) gọi là sự bay hơi.", isCorrect: true },
      { key: "b", text: "Nước đá tan thành nước lỏng ở 0°C là quá trình đông đặc.", isCorrect: false },
      { key: "c", text: "Hơi nước ngưng tụ thành những giọt sương trên lá cây vào ban đêm khi nhiệt độ giảm.", isCorrect: true },
      { key: "d", text: "Trong suốt quá trình nóng chảy của nước đá nguyên chất, nhiệt độ tiếp tục tăng liên tục.", isCorrect: false }
    ],
    correctAnswer: "{\"a\": true, \"b\": false, \"c\": true, \"d\": false}",
    explanation: "a: Đúng; b: Sai (đây là nóng chảy); c: Đúng; d: Sai (nhiệt độ giữ không đổi 0°C khi đang nóng chảy).",
    rationale: "Học sinh hiểu các khái niệm chuyển thể và áp dụng phân tích các nhận định thực tế (Thông hiểu - M2).",
    score: 1.0,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 6 Kết nối tri thức", lessonName: "Bài 10: Các thể của chất" },
    tags: ["CHEMISTRY", "SUBSTANCE_CHANGE", "M2", "TRUE_FALSE"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn6-b05-01",
    grade: 6,
    semester: "HK1",
    lessonId: "lesson-6-5",
    topic: "Đo chiều dài",
    subjectArea: "PHYSICS",
    contentDomain: "ENERGY_CHANGE",
    learningRequirementText: "Xác định được giới hạn đo (GHĐ) và độ chia nhỏ nhất (ĐCNN) của thước đo.",
    cognitiveLevel: "M3",
    questionType: "SHORT_ANSWER",
    difficulty: "MEDIUM",
    questionText: "Một thước kẻ có vạch số 0 trùng mép thước và vạch số lớn nhất là 30 cm. Giữa vạch 1 cm và 2 cm có 10 khoảng chia đều nhau. Giá trị độ chia nhỏ nhất (ĐCNN) của thước này bằng bao nhiêu milimet (mm)?",
    correctAnswer: "1",
    explanation: "Khoảng cách giữa hai vạch liên tiếp là 1 cm / 10 = 0.1 cm = 1 mm. Vậy ĐCNN = 1 mm.",
    rationale: "Học sinh vận dụng quy tắc tính ĐCNN trên dụng cụ đo chiều dài thực tế (Vận dụng - M3).",
    score: 0.5,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 6 Kết nối tri thức", lessonName: "Bài 5: Đo chiều dài" },
    tags: ["PHYSICS", "ENERGY_CHANGE", "M3", "SHORT_ANSWER"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn6-b20-01",
    grade: 6,
    semester: "HK1",
    lessonId: "lesson-6-20",
    topic: "Sự lớn lên và sinh sản của tế bào",
    subjectArea: "BIOLOGY",
    contentDomain: "LIVING_THINGS",
    learningRequirementText: "Nêu được ý nghĩa của sự lớn lên và sinh sản của tế bào đối với sinh vật.",
    cognitiveLevel: "M3",
    questionType: "ESSAY",
    difficulty: "MEDIUM",
    questionText: "Trình bày ý nghĩa của sự lớn lên và sinh sản của tế bào đối với cơ thể sinh vật. Khi một người bị trầy xước da ở tay, sau một thời gian vết thương lành lại, hãy giải thích cơ chế tế bào giúp vết thương lành.",
    correctAnswer: "Biểu điểm chi tiết:\n1. Ý nghĩa: Tế bào lớn lên và phân chia giúp cơ thể tăng trưởng kích thước, khối lượng và thay thế các tế bào già, tế bào bị tổn thương (1.0đ).\n2. Giải thích: Khi da bị trầy xước, các tế bào da ở mép vết thương thực hiện phân chia (sinh sản) tạo ra các tế bào mới, dần dần lấp đầy và chữa lành vết thương (1.0đ).",
    explanation: "Sự phân chia tế bào là cơ sở cho sự lớn lên của sinh vật và làm lành các vết thương mô mềm.",
    rationale: "Vận dụng kiến thức phân chia tế bào vào hiện tượng sinh học thực tế ở người (Vận dụng - M3).",
    score: 1.0,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 6 Kết nối tri thức", lessonName: "Bài 20: Sự phân chia tế bào" },
    tags: ["BIOLOGY", "LIVING_THINGS", "M3", "ESSAY"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= KHTN 7 =================
  {
    id: "q-khtn7-b02-01",
    grade: 7,
    semester: "HK1",
    lessonId: "lesson-7-2",
    topic: "Nguyên tử",
    subjectArea: "CHEMISTRY",
    contentDomain: "SUBSTANCE_CHANGE",
    learningRequirementText: "Nêu được cấu tạo của nguyên tử gồm hạt nhân mang điện tích dương và vỏ electron mang điện tích âm.",
    cognitiveLevel: "M1",
    questionType: "MCQ",
    difficulty: "EASY",
    questionText: "Trong nguyên tử, các hạt mang điện tích âm nằm ở lớp vỏ là hạt gì?",
    options: [
      { key: "A", text: "Proton" },
      { key: "B", text: "Neutron" },
      { key: "C", text: "Electron" },
      { key: "D", text: "Hạt nhân" }
    ],
    correctAnswer: "C",
    explanation: "Electron là hạt mang điện tích âm (-), chuyển động xung quanh hạt nhân nguyên tử.",
    rationale: "Nhận biết các loại hạt cấu tạo nên nguyên tử theo mô hình Rutherford - Bohr (Nhận biết - M1).",
    score: 0.25,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 7 Kết nối tri thức", lessonName: "Bài 2: Nguyên tử" },
    tags: ["CHEMISTRY", "SUBSTANCE_CHANGE", "M1", "MCQ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn7-b08-01",
    grade: 7,
    semester: "HK1",
    lessonId: "lesson-7-8",
    topic: "Tốc độ chuyển động",
    subjectArea: "PHYSICS",
    contentDomain: "ENERGY_CHANGE",
    learningRequirementText: "Tính được tốc độ chuyển động dựa vào công thức v = s / t.",
    cognitiveLevel: "M3",
    questionType: "SHORT_ANSWER",
    difficulty: "MEDIUM",
    questionText: "Một bạn học sinh đi xe đạp trên quãng đường dài 3,6 km hết thời gian 15 phút. Tốc độ chuyển động của bạn học sinh đó bằng bao nhiêu km/h?",
    correctAnswer: "14.4",
    explanation: "Đổi 15 phút = 0,25 giờ. Tốc độ v = s / t = 3,6 / 0,25 = 14,4 km/h.",
    rationale: "Vận dụng công thức tính tốc độ và kĩ năng đổi đơn vị thời gian (Vận dụng - M3).",
    score: 0.5,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 7 Kết nối tri thức", lessonName: "Bài 8: Tốc độ" },
    tags: ["PHYSICS", "ENERGY_CHANGE", "M3", "SHORT_ANSWER"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn7-b22-01",
    grade: 7,
    semester: "HK1",
    lessonId: "lesson-7-22",
    topic: "Quang hợp ở thực vật",
    subjectArea: "BIOLOGY",
    contentDomain: "LIVING_THINGS",
    learningRequirementText: "Viết được phương trình quang hợp dạng chữ. Nêu được vai trò của quang hợp.",
    cognitiveLevel: "M2",
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    questionText: "Khi nghiên cứu về quá trình quang hợp ở cây xanh, các nhận định sau đây là đúng hay sai?",
    options: [
      { key: "a", text: "Nước và khí carbon dioxide là nguyên liệu đầu vào của quang hợp.", isCorrect: true },
      { key: "b", text: "Chất hữu cơ (glucose) và khí oxygen là sản phẩm tạo thành của quang hợp.", isCorrect: true },
      { key: "c", text: "Quang hợp chỉ có thể diễn ra vào ban đêm khi có nhiều hơi ẩm.", isCorrect: false },
      { key: "d", text: "Năng lượng ánh sáng Mặt Trời được chuyển hóa thành hóa năng tích lũy trong chất hữu cơ.", isCorrect: true }
    ],
    correctAnswer: "{\"a\": true, \"b\": true, \"c\": false, \"d\": true}",
    explanation: "a: Đúng; b: Đúng; c: Sai (cần ánh sáng Mặt Trời nên chủ yếu diễn ra ban ngày); d: Đúng.",
    rationale: "Thông hiểu nguyên liệu, sản phẩm và bản chất chuyển hóa năng lượng trong quang hợp (Thông hiểu - M2).",
    score: 1.0,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 7 Kết nối tri thức", lessonName: "Bài 22: Quang hợp" },
    tags: ["BIOLOGY", "LIVING_THINGS", "M2", "TRUE_FALSE"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= KHTN 8 =================
  {
    id: "q-khtn8-b02-01",
    grade: 8,
    semester: "HK1",
    lessonId: "lesson-8-2",
    topic: "Phản ứng hóa học",
    subjectArea: "CHEMISTRY",
    contentDomain: "SUBSTANCE_CHANGE",
    learningRequirementText: "Nêu được khái niệm phản ứng hóa học, chất đầu và sản phẩm.",
    cognitiveLevel: "M1",
    questionType: "MCQ",
    difficulty: "EASY",
    questionText: "Dấu hiệu nào sau đây chứng tỏ có phản ứng hóa học xảy ra?",
    options: [
      { key: "A", text: "Có sự xuất hiện chất mới (kết tủa, chất khí hoặc đổi màu)" },
      { key: "B", text: "Chất rắn bị đập vụn thành bột nhỏ" },
      { key: "C", text: "Nước đá tan chảy thành nước lỏng" },
      { key: "D", text: "Hòa tan muối ăn vào nước" }
    ],
    correctAnswer: "A",
    explanation: "Bản chất của phản ứng hóa học là có sự biến đổi chất này thành chất khác (xuất hiện chất mới).",
    rationale: "Nhận biết dấu hiệu chứng tỏ phản ứng hóa học xảy ra phân biệt với hiện tượng vật lí (Nhận biết - M1).",
    score: 0.25,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 8 Kết nối tri thức", lessonName: "Bài 2: Phản ứng hóa học" },
    tags: ["CHEMISTRY", "SUBSTANCE_CHANGE", "M1", "MCQ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn8-b13-01",
    grade: 8,
    semester: "HK1",
    lessonId: "lesson-8-13",
    topic: "Khối lượng riêng",
    subjectArea: "PHYSICS",
    contentDomain: "ENERGY_CHANGE",
    learningRequirementText: "Tính được khối lượng riêng theo công thức D = m / V.",
    cognitiveLevel: "M3",
    questionType: "SHORT_ANSWER",
    difficulty: "MEDIUM",
    questionText: "Một khối kim loại hình lập phương cạnh 2 cm có khối lượng 56 gam. Khối lượng riêng của kim loại đó bằng bao nhiêu g/cm³?",
    correctAnswer: "7",
    explanation: "Thể tích V = 2 x 2 x 2 = 8 cm³. Khối lượng riêng D = m / V = 56 / 8 = 7 g/cm³.",
    rationale: "Vận dụng công thức tính thể tích hình lập phương và công thức khối lượng riêng (Vận dụng - M3).",
    score: 0.5,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 8 Kết nối tri thức", lessonName: "Bài 13: Khối lượng riêng" },
    tags: ["PHYSICS", "ENERGY_CHANGE", "M3", "SHORT_ANSWER"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ================= KHTN 9 =================
  {
    id: "q-khtn9-b02-01",
    grade: 9,
    semester: "HK1",
    lessonId: "lesson-9-2",
    topic: "Động năng. Thế năng",
    subjectArea: "PHYSICS",
    contentDomain: "ENERGY_CHANGE",
    learningRequirementText: "Nêu được khái niệm động năng, thế năng trọng trường.",
    cognitiveLevel: "M1",
    questionType: "MCQ",
    difficulty: "EASY",
    questionText: "Dạng năng lượng mà một vật có được do nó đang chuyển động được gọi là gì?",
    options: [
      { key: "A", text: "Thế năng hấp dẫn" },
      { key: "B", text: "Động năng" },
      { key: "C", text: "Nhiệt năng" },
      { key: "D", text: "Hóa năng" }
    ],
    correctAnswer: "B",
    explanation: "Năng lượng mà vật có được do chuyển động gọi là động năng.",
    rationale: "Nhận biết khái niệm động năng trong cơ học (Nhận biết - M1).",
    score: 0.25,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 9 Kết nối tri thức", lessonName: "Bài 2: Động năng thế năng" },
    tags: ["PHYSICS", "ENERGY_CHANGE", "M1", "MCQ"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn9-b18-01",
    grade: 9,
    semester: "HK1",
    lessonId: "lesson-9-18",
    topic: "Tính chất chung của kim loại",
    subjectArea: "CHEMISTRY",
    contentDomain: "SUBSTANCE_CHANGE",
    learningRequirementText: "Trình bày được tính chất hóa học của kim loại khi tác dụng với dung dịch acid.",
    cognitiveLevel: "M2",
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    questionText: "Cho các mẩu kim loại kẽm (Zn), đồng (Cu), sắt (Fe), nhôm (Al) tác dụng với dung dịch axit clohiđric (HCl) loãng. Các nhận định sau đây là đúng hay sai?",
    options: [
      { key: "a", text: "Kim loại kẽm (Zn) tan dần và có bọt khí không màu (H₂) thoát ra.", isCorrect: true },
      { key: "b", text: "Kim loại đồng (Cu) phản ứng mãnh liệt tạo thành dung dịch màu xanh lam và khí H₂.", isCorrect: false },
      { key: "c", text: "Kim loại sắt (Fe) phản ứng tạo ra dung dịch muối sắt(II) clorua FeCl₂.", isCorrect: true },
      { key: "d", text: "Khí sinh ra trong các phản ứng trên làm que đóm bùng cháy rực rỡ.", isCorrect: false }
    ],
    correctAnswer: "{\"a\": true, \"b\": false, \"c\": true, \"d\": false}",
    explanation: "a: Đúng (Zn + 2HCl -> ZnCl2 + H2); b: Sai (Cu đứng sau H nên không phản ứng); c: Đúng; d: Sai (H2 cháy tiếng nổ nhỏ, không phải O2 làm que đóm bùng cháy).",
    rationale: "Thông hiểu tính chất kim loại đứng trước và sau hiđro trong dãy hoạt động hóa học (Thông hiểu - M2).",
    score: 1.0,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 9 Kết nối tri thức", lessonName: "Bài 18: Kim loại" },
    tags: ["CHEMISTRY", "SUBSTANCE_CHANGE", "M2", "TRUE_FALSE"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "q-khtn9-b36-01",
    grade: 9,
    semester: "HK1",
    lessonId: "lesson-9-36",
    topic: "Khái quát về di truyền học",
    subjectArea: "BIOLOGY",
    contentDomain: "LIVING_THINGS",
    learningRequirementText: "Nêu được khái niệm di truyền, biến dị và vai trò của gene.",
    cognitiveLevel: "M3",
    questionType: "ESSAY",
    difficulty: "HARD",
    questionText: "Phân biệt hiện tượng di truyền và hiện tượng biến dị. Lấy 2 ví dụ thực tế ở người để minh họa cho mỗi hiện tượng. Giải thích tại sao con cái sinh ra vừa có những đặc điểm giống bố mẹ, vừa có những đặc điểm khác bố mẹ.",
    correctAnswer: "Biểu điểm chi tiết:\n1. Phân biệt: Di truyền là sự truyền đạt các tính trạng từ bố mẹ cho thế hệ con cháu. Biến dị là hiện tượng con sinh ra có những đặc điểm khác bố mẹ và khác nhau giữa các cá thể con (0.5đ).\n2. Ví dụ: Di truyền: bố mẹ mắt đen con sinh ra mắt đen; Biến dị: bố mẹ tóc thẳng con sinh ra tóc xoăn (0.5đ).\n3. Giải thích: Con cái nhận vật chất di truyền (gene) từ cả bố và mẹ qua thụ tinh (tính giống nhau), đồng thời qua giảm phân và thụ tinh xảy ra sự tái tổ hợp vật chất di truyền và đột biến tạo nên những tổ hợp tính trạng mới (tính khác nhau) (1.0đ).",
    explanation: "Sự kết hợp giữa di truyền và biến dị tạo nên sự đa dạng phong phú của thế giới sinh vật.",
    rationale: "Vận dụng kiến thức cơ chế di truyền và biến dị để giải thích hiện tượng thực tiễn ở người (Vận dụng - M3).",
    score: 1.0,
    sourceLevel: "TEXTBOOK",
    sourceCitation: { documentName: "SGK KHTN 9 Kết nối tri thức", lessonName: "Bài 36: Di truyền học" },
    tags: ["BIOLOGY", "LIVING_THINGS", "M3", "ESSAY"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

store.questionBank = seedQuestions;
fs.writeFileSync(storePath, JSON.stringify(store, null, 2), 'utf8');
console.log(`Successfully seeded ${seedQuestions.length} standard questions into database/local_store.json`);
